Support Copycat blocks copying blast resistance
Cannoneers-of-Create/CreateBigCannons pull request #447
Opened 2024-01-26 17:22 UTC by Endalion

Added a `getHardness` method which takes Create Copycat blocks into consideration, also checking the block/tag map on the copied block.
The parameters differ so I only changed the resistance tool as an example, if this patch is satisfactory then I'll propagate to the rest

2024-01-27 00:44 UTC, rbasamoyai commented
Could be in 0.5.4, we'll see

2024-01-27 00:45 UTC, rbasamoyai commented
Although, once again I think it may be interesting to add a mixin interface to CopycatBlock - this would make mod compat easier

2024-01-27 01:38 UTC, Endalion commented
Hm, I'm not quite sure how to mixin it that way but I'll try it out

2024-01-28 19:48 UTC, Endalion commented
wow mixins are powerful 👍 I also changed the rest of the hardness checks to follow the new method

2024-01-29 01:10 UTC, rbasamoyai commented on common/src/main/java/rbasamoyai/createbigcannons/mixin/CopycatMixin.java
> +	public @NotNull Block createBigCannons$getActualBlock(BlockState state, Level level, BlockPos pos) {
Use Javax notnull

2024-01-29 01:10 UTC, rbasamoyai commented on common/src/main/java/rbasamoyai/createbigcannons/munitions/config/PropertiesMimicTypeBlock.java
> +	@NotNull Block createBigCannons$getActualBlock(BlockState state, Level level, BlockPos pos);
Ditto

2024-01-29 01:11 UTC, rbasamoyai requested changes
Use javax nonnull instead of JetBrians NotNull

2024-02-08 00:32 UTC, rbasamoyai approved these changes

2024-02-16 01:28 UTC, merged